import { ArrowUpRight, Clock3, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Movie } from '../types/movie'

export function MovieCard({ movie }: { movie: Movie }) {
  return <article className="group min-w-0 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.045] shadow-xl shadow-black/10 transition duration-300 hover:-translate-y-1 hover:border-violet-400/40 hover:bg-white/[0.08]">
    <div className={`relative aspect-[3/4.2] overflow-hidden ${movie.posterClass}`}><div className="absolute inset-0 flex flex-col justify-between p-5"><span className="max-w-[10rem] text-[10px] font-medium uppercase tracking-[0.2em] text-white/70">{movie.posterKicker}</span><strong className="whitespace-pre-line text-3xl font-black leading-[0.86] tracking-[-0.08em] text-white drop-shadow-lg">{movie.posterMark}</strong></div><span className="absolute right-3 top-3 rounded-full bg-black/35 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-white/90 backdrop-blur">{movie.releaseLabel}</span></div>
    <div className="p-4"><div className="flex min-h-14 items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-semibold text-white">{movie.title}</h3><p className="mt-1 truncate text-xs text-slate-400">{movie.genre}</p></div>{movie.rating && <span className="flex shrink-0 items-center gap-1 text-xs font-semibold text-amber-300"><Star size={13} fill="currentColor" />{movie.rating}</span>}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-400"><span className="flex items-center gap-1.5"><Clock3 size={14} />{movie.duration}</span><div className="flex items-center gap-3"><Link className="flex items-center gap-1 font-semibold text-violet-300 transition group-hover:text-violet-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-300" to={`/movies/${movie.id}`}>Details <ArrowUpRight size={14} /></Link>{movie.releaseLabel === 'Now showing' && <Link className="rounded-lg bg-violet-500 px-3 py-2 font-semibold text-white hover:bg-violet-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-300" to={`/movies/${movie.id}/showtimes`}>Book</Link>}</div></div></div>
  </article>
}
