export const eventsData = [
  {
    id: 'global-music-fest',
    indexNumber: '01',
    title: 'Global Music Fest',
    tagline: 'A Massive live festival experience',
    verticalTag: 'Booking Open / This Weekend',
    scheduleStatus: '10 Oct',
    scheduleLabel: 'Next Events',
    heroBadge: 'Watch Now',
    badgeTopRight: '10 Oct',
    rating: 4.5,
    genre: 'music festival, live concert, outdoor',
    genreTags: ['Music', 'Concerts', 'Festivals'],
    formats: ['LIVE HD', '18+'],
    description: "Experience the year's biggest celebration of music, culture, and art featuring global headliners, spectacular laser shows, and multiple immersive stages.",
    posterImage: '/images/events/global-music-fest.jpg',
    backdropImage: '/images/backgrounds/festival_hero.jpg',
    primaryAction: {
      label: 'Book Now',
      icon: 'ticket',
      link: '/book/global-music-fest',
    },
    secondaryAction: {
      label: 'More Info',
      link: '/events/global-music-fest',
    },
    statusCategory: 'now',
    duration: '2 Days (Oct 10-11)',
    venue: 'Sepang International Circuit Arena',
    priceRM: 180,
    category: 'event',
  },
  {
    id: 'comedy-show',
    indexNumber: '02',
    title: 'Comedy Show',
    tagline: 'Unfiltered night of pure laughter',
    verticalTag: 'Booking Open / This Weekend',
    scheduleStatus: 'Tonight',
    scheduleLabel: 'Live Tonight',
    heroBadge: 'STANDUP LIVE',
    badgeTopRight: 'Tonight',
    rating: 4.8,
    genre: 'stand-up comedy, live, solo',
    genreTags: ['Comedy'],
    formats: ['LIVE HD', '16+'],
    description: 'Top-tier international stand-up comedians bring brand-new material, razor-sharp crowd work, and hilarious anecdotes to an intimate amphitheater setting.',
    posterImage: '/images/events/comedy-show.jpg',
    backdropImage: '/images/backgrounds/comedy_hero.jpg',
    primaryAction: {
      label: 'Book Now',
      icon: 'ticket',
      link: '/book/comedy-show',
    },
    secondaryAction: {
      label: 'More Info',
      link: '/events/comedy-show',
    },
    statusCategory: 'now',
    duration: '2 Hours (8:30 PM)',
    venue: 'Plenary Hall, KL Convention Centre',
    priceRM: 85,
    category: 'event',
  },
  {
    id: 'tech-summit',
    indexNumber: '03',
    title: 'Asia Tech Summit 2024',
    tagline: 'The future of AI, robotics and quantum computing',
    verticalTag: 'Tickets Selling Fast',
    scheduleStatus: '15 Nov',
    scheduleLabel: 'Upcoming Summit',
    heroBadge: 'KEYNOTE EXCLUSIVE',
    badgeTopRight: '15 Nov',
    rating: 4.9,
    genre: 'technology, conference, exhibition',
    genreTags: ['Tech', 'Conferences', 'Innovation'],
    formats: ['HYBRID', 'ALL AGES'],
    description: 'Connect with visionary founders, VC partners, and tech pioneers across two power-packed days featuring hands-on AI workshops and startup pitch showcases.',
    posterImage: '/images/events/tech-summit.jpg',
    backdropImage: '/images/backgrounds/tech_hero.jpg',
    primaryAction: {
      label: 'Register Pass',
      icon: 'ticket',
      link: '/book/tech-summit',
    },
    secondaryAction: {
      label: 'Summit Agenda',
      link: '/events/tech-summit',
    },
    statusCategory: 'upcoming',
    duration: 'Full Day (9:00 AM - 6:00 PM)',
    venue: 'MITEC Grand Ballroom, Kuala Lumpur',
    priceRM: 250,
    category: 'event',
  },
  {
    id: 'art-exhibition',
    indexNumber: '04',
    title: 'Immersive Art Exhibition',
    tagline: 'Step into vivid living masterpieces',
    verticalTag: 'Daily Screenings Available',
    scheduleStatus: 'Open Daily',
    scheduleLabel: 'Now Showing',
    heroBadge: 'IMMERSIVE 360',
    badgeTopRight: 'Daily',
    rating: 4.7,
    genre: 'art, interactive, visual exhibition',
    genreTags: ['Art', 'Interactive', 'Exhibitions'],
    formats: ['360 PROJECTION', 'FAMILY FRIENDLY'],
    description: 'A 360-degree digital multisensory journey bringing classical Impressionist works and surrealist dreamscapes alive with soundscapes and light design.',
    posterImage: '/images/events/art-exhibition.jpg',
    backdropImage: '/images/backgrounds/art_hero.jpg',
    primaryAction: {
      label: 'Select Slots',
      icon: 'ticket',
      link: '/book/art-exhibition',
    },
    secondaryAction: {
      label: 'Gallery Preview',
      link: '/events/art-exhibition',
    },
    statusCategory: 'now',
    duration: '90 Minutes Entry',
    venue: 'RexKL Immersive Space',
    priceRM: 60,
    category: 'event',
  },
];

export const streamsData = [
  {
    id: 'house-of-the-dragon',
    indexNumber: '01',
    title: 'House of the Dragon',
    scheduleStatus: 'New Episode',
    scheduleLabel: 'Watch Now',
    heroBadge: 'Watch Now',
    badgeTopRight: 'New Episode',
    rating: 4.5,
    genre: 'action, fantasy, drama',
    genreTags: ['Fantasy', 'Drama', 'Action'],
    formats: ['4K HDR', 'R-18'],
    description: 'When the Targaryen dynasty is at its peak, the sibling struggle for the Iron Throne threatens to tear the kingdom apart...',
    posterImage: '/images/streams/house-of-the-dragon.jpg',
    backdropImage: '/images/backgrounds/dragon_hero.jpg',
    primaryAction: {
      label: 'Watch Now',
      icon: 'play',
      link: '/streams/house-of-the-dragon',
    },
    secondaryAction: {
      label: 'More Info',
      link: '/streams/house-of-the-dragon',
    },
    statusCategory: 'now',
  },
  {
    id: 'the-last-of-us',
    indexNumber: '02',
    title: 'The Last of Us',
    scheduleStatus: 'New Episode',
    scheduleLabel: 'Watch Now',
    heroBadge: 'ORIGINAL SERIES',
    badgeTopRight: 'New Episode',
    rating: 4.9,
    genre: 'drama, thriller, post-apocalyptic',
    genreTags: ['Drama', 'Action', 'Sci-Fi'],
    formats: ['4K HDR', 'TV-MA'],
    description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    posterImage: '/images/streams/the-last-of-us.jpg',
    backdropImage: '/images/backgrounds/tlou_hero.jpg',
    primaryAction: {
      label: 'Watch Now',
      icon: 'play',
      link: '/streams/the-last-of-us',
    },
    secondaryAction: {
      label: 'More Info',
      link: '/streams/the-last-of-us',
    },
    statusCategory: 'now',
  },
  {
    id: 'stranger-things',
    indexNumber: '03',
    title: 'Stranger Things',
    scheduleStatus: 'Final Season',
    scheduleLabel: 'Watch Now',
    heroBadge: 'NETFLIX ORIGINAL',
    badgeTopRight: 'Final Season',
    rating: 4.8,
    genre: 'sci-fi, horror, drama',
    genreTags: ['Sci-Fi', 'Horror', 'Drama'],
    formats: ['4K Dolby Vision', '16+'],
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    posterImage: '/images/streams/stranger-things.jpg',
    backdropImage: '/images/backgrounds/stranger_hero.jpg',
    primaryAction: {
      label: 'Watch Now',
      icon: 'play',
      link: '/streams/stranger-things',
    },
    secondaryAction: {
      label: 'More Info',
      link: '/streams/stranger-things',
    },
    statusCategory: 'now',
  },
];

export const playsData = [
  {
    id: 'hamilton',
    indexNumber: '01',
    title: 'Hamilton: The Musical',
    tagline: 'The revolutionary Broadway musical phenomenon',
    verticalTag: 'Limited Season Run',
    scheduleStatus: 'Oct 15 - Nov 30',
    scheduleLabel: 'Broadway Asia Tour',
    heroBadge: 'BROADWAY ORIGINAL',
    badgeTopRight: 'Oct 15',
    rating: 4.9,
    genre: 'broadway musical, hip-hop, historical drama',
    genreTags: ['Musical', 'Broadway', 'Drama'],
    formats: ['LIVE THEATRE', 'ALL AGES'],
    description: 'Lin-Manuel Miranda\'s Pulitzer Prize-winning masterpiece tells the story of American founding father Alexander Hamilton through a score that blends hip-hop, jazz, R&B, and Broadway.',
    posterImage: '/images/plays/hamilton.jpg',
    backdropImage: '/images/backgrounds/hamilton_hero.jpg',
    primaryAction: {
      label: 'Book Seats',
      icon: 'ticket',
      link: '/book/hamilton',
    },
    secondaryAction: {
      label: 'Play Details',
      link: '/plays/hamilton',
    },
    statusCategory: 'now',
    duration: '2h 50m (incl. 20m interval)',
    venue: 'Istana Budaya, Panggung Sari Theatre, KL',
    priceRM: 220,
    category: 'play',
  },
  {
    id: 'phantom-opera',
    indexNumber: '02',
    title: 'The Phantom of the Opera',
    tagline: 'The timeless musical romance of the Paris Opera House',
    verticalTag: 'Final Malaysian Shows',
    scheduleStatus: 'Tonight - Sun',
    scheduleLabel: 'West End Tour',
    heroBadge: 'WEST END HIT',
    badgeTopRight: 'Tonight',
    rating: 4.8,
    genre: 'opera, musical romance, gothic drama',
    genreTags: ['Musical', 'Romance', 'Drama'],
    formats: ['ORCHESTRA LIVE', '12+'],
    description: 'Andrew Lloyd Webber\'s spellbinding musical tells the tragic tale of a masked musical genius dwelling in the catacombs beneath the Paris Opera House.',
    posterImage: '/images/plays/phantom-opera.jpg',
    backdropImage: '/images/backgrounds/phantom_hero.jpg',
    primaryAction: {
      label: 'Book Seats',
      icon: 'ticket',
      link: '/book/phantom-opera',
    },
    secondaryAction: {
      label: 'Play Details',
      link: '/plays/phantom-opera',
    },
    statusCategory: 'now',
    duration: '2h 30m',
    venue: 'Plenary Theatre, Kuala Lumpur',
    priceRM: 190,
    category: 'play',
  },
];

export const sportsData = [
  {
    id: 'f1-night-race',
    indexNumber: '01',
    title: 'Formula 1 Night Grand Prix',
    tagline: 'High-speed street racing under dazzling floodlights',
    verticalTag: 'Grandstand Passes Available',
    scheduleStatus: 'Race Weekend',
    scheduleLabel: 'Live Circuit',
    heroBadge: 'F1 WORLD CHAMPIONSHIP',
    badgeTopRight: 'This Weekend',
    rating: 4.9,
    genre: 'motorsport, f1, racing',
    genreTags: ['Racing', 'Formula 1', 'Motorsport'],
    formats: ['CIRCUIT LIVE', 'ALL AGES'],
    description: 'Experience 20 world-class drivers navigating challenging tight turns at speeds exceeding 300 km/h, accompanied by electric post-race concerts.',
    posterImage: '/images/sports/f1-night-race.jpg',
    backdropImage: '/images/backgrounds/f1_hero.jpg',
    primaryAction: {
      label: 'Book Grandstand',
      icon: 'ticket',
      link: '/book/f1-night-race',
    },
    secondaryAction: {
      label: 'Circuit Details',
      link: '/sports/f1-night-race',
    },
    statusCategory: 'now',
    duration: '3 Days Trackside Experience',
    venue: 'Marina Bay Street Circuit',
    priceRM: 350,
    category: 'sport',
  },
  {
    id: 'premier-league',
    indexNumber: '02',
    title: 'Premier League Live Screening Derby',
    tagline: 'Massive mega-screen stadium experience with live crowd anthems',
    verticalTag: 'Matchday Screening',
    scheduleStatus: 'Saturday 8:00 PM',
    scheduleLabel: 'Live Screening',
    heroBadge: 'DERBY NIGHT',
    badgeTopRight: 'Saturday',
    rating: 4.7,
    genre: 'football, premier league, stadium screening',
    genreTags: ['Football', 'Sports', 'Derby'],
    formats: ['4K GIANT LED', 'ALL AGES'],
    description: 'Catch the high-stakes Manchester derby on a 40-foot outdoor LED screen with crystal-clear line-array sound and interactive fan giveaways.',
    posterImage: '/images/sports/premier-league.jpg',
    backdropImage: '/images/backgrounds/football_hero.jpg',
    primaryAction: {
      label: 'Book Entry',
      icon: 'ticket',
      link: '/book/premier-league',
    },
    secondaryAction: {
      label: 'Match Info',
      link: '/sports/premier-league',
    },
    statusCategory: 'now',
    duration: 'Matchday + Post-Match Analysis',
    venue: 'Bukit Jalil Stadium Fan Arena',
    priceRM: 45,
    category: 'sport',
  },
];

export const activitiesData = [
  {
    id: 'indoor-skydiving',
    indexNumber: '01',
    title: 'Indoor Skydiving Wind Tunnel',
    tagline: 'Feel true free-fall adrenaline in a state-of-the-art vertical wind tunnel',
    verticalTag: 'Open 7 Days A Week',
    scheduleStatus: 'Slots Available Daily',
    scheduleLabel: 'Action Sports',
    heroBadge: 'EXTREME ADVENTURE',
    badgeTopRight: 'Daily',
    rating: 4.8,
    genre: 'adventure, skydiving, family experience',
    genreTags: ['Adventure', 'Extreme', 'Family'],
    formats: ['ALL AGES', 'CERTIFIED INSTRUCTORS'],
    description: 'Experience pure flight without jumping out of an aircraft! Certified wind tunnel instructors guide you through 2 adrenaline-packed flight sessions.',
    posterImage: '/images/backgrounds/tech_hero.jpg',
    backdropImage: '/images/backgrounds/tech_hero.jpg',
    primaryAction: {
      label: 'Book Flight',
      icon: 'ticket',
      link: '/book/indoor-skydiving',
    },
    secondaryAction: {
      label: 'View Packages',
      link: '/activities/indoor-skydiving',
    },
    statusCategory: 'now',
    duration: '60 Minutes (2 Flights + Briefing)',
    venue: 'Windlab Skydiving 1 Utama',
    priceRM: 110,
    category: 'activity',
  },
];

export const offersData = [
  {
    id: 'maybank-1for1',
    title: 'Maybank 1-for-1 IMAX Movie Tickets',
    code: 'MBBIMAX',
    discount: 'Buy 1 Free 1',
    description: 'Get a complimentary IMAX ticket every Saturday & Sunday with Maybank Cards.',
    validUntil: '31 Dec 2024',
    bannerImage: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&auto=format&fit=crop&q=80',
    category: 'Bank Promo',
  },
  {
    id: 'student-thursday',
    title: 'Student Special: Flat RM14 Tickets',
    code: 'STUDENT14',
    discount: 'Flat RM14',
    description: 'Valid for all standard 2D showtimes on Thursdays before 6:00 PM with valid student ID.',
    validUntil: 'Every Thursday',
    bannerImage: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80',
    category: 'Student Deal',
  },
  {
    id: 'popcorn-combo-50',
    title: '50% Off Jumbo Caramel Popcorn Combo',
    code: 'YUMMY50',
    discount: '50% OFF',
    description: 'Add a Jumbo Popcorn + 2 Large Soft Drinks when booking 2 or more cinema seats online.',
    validUntil: 'Limited Time',
    bannerImage: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=600&auto=format&fit=crop&q=80',
    category: 'Concessions',
  },
  {
    id: 'grabpay-cashback',
    title: 'RM8 Instant Rebate with GrabPay',
    code: 'GRABCINE',
    discount: 'RM8 OFF',
    description: 'Pay via GrabPay on minimum spend of RM40 to enjoy an instant RM8 cashback voucher.',
    validUntil: '15 Nov 2024',
    bannerImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    category: 'E-Wallet',
  },
];
