import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, MapPin, Ticket, XCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { mockBookings, type BookingStatus, type MockBooking } from '../data/bookings'
import { comingSoonMovies, nowShowingMovies } from '../data/movies'
import { mockTheatres } from '../data/showtimes'
import { Footer } from '../components/Footer'
import { Navbar } from '../components/Navbar'

const movies = [...nowShowingMovies, ...comingSoonMovies]
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`
const labels: Record<BookingStatus, string> = { upcoming: 'Upcoming', past: 'Past', cancelled: 'Cancelled' }

function BookingCard({ booking }: { booking: MockBooking }) { const movie = movies.find((item) => item.id === booking.movieId); const theatre = mockTheatres.find((item) => item.id === booking.theatreId); const showtime = theatre?.showtimes.find((item) => item.id === booking.showtimeId); const date = new Date(`${booking.date}T00:00:00`).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' }); const statusStyle = booking.status === 'upcoming' ? 'text-emerald-300 bg-emerald-400/10 border-emerald-300/20' : booking.status === 'cancelled' ? 'text-rose-300 bg-rose-400/10 border-rose-300/20' : 'text-slate-300 bg-white/5 border-white/10'; const StatusIcon = booking.status === 'upcoming' ? CheckCircle2 : booking.status === 'cancelled' ? XCircle : Clock3
  if (!movie || !theatre || !showtime) return null
  return <article className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.045] transition hover:border-violet-400/30"><div className="flex flex-col gap-5 p-5 sm:flex-row"><div className={`relative h-36 w-24 shrink-0 overflow-hidden rounded-xl ${movie.posterClass}`}><div className="absolute inset-0 flex items-end p-3"><strong className="whitespace-pre-line text-lg font-black leading-[0.86] tracking-[-0.08em] text-white">{movie.posterMark}</strong></div></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-semibold text-white">{movie.title}</h3><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-400"><MapPin size={14} className="text-violet-300" />{theatre.name} · {theatre.location}</p></div><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${statusStyle}`}><StatusIcon size={13} />{labels[booking.status]}</span></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><div><p className="text-[10px] uppercase tracking-wider text-slate-500">Date</p><p className="mt-1 text-slate-200">{date}</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-500">Showtime</p><p className="mt-1 text-slate-200">{showtime.label}</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-500">Seats</p><p className="mt-1 text-slate-200">{booking.seats.join(', ')}</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-500">Tickets</p><p className="mt-1 text-slate-200">{booking.seats.length}</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4"><div><span className="text-xs text-slate-500">Reference </span><span className="font-mono text-xs text-violet-200">{booking.reference}</span></div><div className="flex items-center gap-4"><span className="font-semibold text-white">{money(booking.total)}</span><Link to={`/movies/${movie.id}`} className="text-sm font-medium text-violet-300 hover:text-violet-200">View movie</Link></div></div></div></div></article> }

function BookingSection({ status, bookings }: { status: BookingStatus; bookings: MockBooking[] }) { return <section><div className="mb-4 flex items-center gap-2"><Ticket size={19} className="text-violet-300" /><h2 className="text-xl font-bold text-white">{labels[status]} bookings</h2></div>{bookings.length ? <div className="space-y-4">{bookings.map((booking) => <BookingCard key={booking.reference} booking={booking} />)}</div> : <div className="rounded-2xl border border-dashed border-white/15 p-10 text-center"><CalendarDays className="mx-auto mb-3 text-slate-600" size={25} /><p className="font-medium text-slate-300">No {status} bookings</p><p className="mt-1 text-sm text-slate-500">Your {status} movie bookings will appear here.</p></div>}</section> }

export function MyBookingsPage() { return <div className="min-h-screen bg-[#080b17] text-slate-200"><Navbar /><main className="mx-auto max-w-5xl px-5 pb-16 pt-28 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-violet-300">Customer area</p><h1 className="mt-2 text-4xl font-black tracking-tight text-white">My bookings</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">A demonstration view of your movie tickets. These records are temporary mock data and are not connected to a backend.</p></div><Link to="/" className="inline-flex items-center gap-2 self-start rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold text-slate-300 hover:border-violet-400/40 hover:text-white sm:self-auto"><ArrowLeft size={16} />Return home</Link></div><div className="mt-10 space-y-12"><BookingSection status="upcoming" bookings={mockBookings.filter((booking) => booking.status === 'upcoming')} /><BookingSection status="past" bookings={mockBookings.filter((booking) => booking.status === 'past')} /><BookingSection status="cancelled" bookings={mockBookings.filter((booking) => booking.status === 'cancelled')} /></div></main><Footer /></div> }
